### ISSUE TITLE
Migrate to Qiskit 1.0

### ISSUE THREAD

**Issue by frankharkins** [JanLahmann/RasQberry#150]
I'm making this issue because this project is part of the [Qiskit ecosystem](https://qiskit.github.io/ecosystem/).

As of June 2024, we're introducing a requirement that all projects are compatible with Qiskit 1.0. New users will be using Qiskit 1.0 and we want to make sure any projects we guide them to work straight away.

See our [migration guide](https://docs.quantum.ibm.com/api/migration-guides). and let me know if you need any support (such as answering questions about Qiskit or code review). With Qiskit's new stability policy, this should be the last change needed for a while.

In June, we will test out your project and remove it if it doesn't work with Qiskit 1.0. This includes cases in which we can't get the project working because the documentation is lacking. We do value your project so let me know if you need any help migrating or have any other concerns.

**Comment by JanLahmann** [comment]
Decision was to stay with Qiskit 0.x on 32-bit bullseye OS, and install Qiskit 1.0.x on 64-bit Bookworm OS.
This is enabled by commit https://github.com/JanLahmann/RasQberry/commit/085ede9b28fe6a343180936de3a7a183d530a449
