### ISSUE TITLE
description for enabling WLAN on RasQberry

### ISSUE THREAD

**Issue by JanLahmann** [JanLahmann/RasQberry#32]
A RasQberry that is using a pre-built SD card image will be "offline" - and not be able to connect a new (local) WLAN.
A description is needed how to re-gain access to the RasQberry, using the touch display only (and no ssh access, etc).

**Comment by m0mms** [comment]
this: https://github.com/BlokasLabs/patchbox-os-gen
there is a single pushbutton on the patchbox, which can be configured to do a whole vareity of things, depending on the way the button is pressed:
one or more short presses
presses of 1, 3 and 5 seconds
what happens is determined by a config file, and can include, for example, enabling a disabling a wlan hotspot, shutdown, among many other things.
