### ISSUE TITLE
12 leds connect to raspberry pi4

### ISSUE THREAD

**Issue by hasanakalin** [JanLahmann/RasQberry#38]
I found 12 led ring and bought them.how do i connect this to raspberry. Could you tell and show us step by step how to connect with visuals?and what is the run command?

**Comment by hasanakalin** [comment]
I bought the Neopixel 12 ring light. which inputs correct do I need soldering and which inputs of raspberry pi4 do I connect?

![IMG_0440](https://user-images.githubusercontent.com/37351958/106594225-dfbf7900-6562-11eb-9005-8c2a20b895b6.jpg)
![IMG_0439](https://user-images.githubusercontent.com/37351958/106594232-e2ba6980-6562-11eb-9e9a-95a094a38feb.jpg)

**Comment by JanLahmann** [comment]
Yes, this LED ring is perfect.
The IN, VCC and GND connectors are correct.

With the command `pinout` you can query the Raspberry Pi GPIO pin-out information.

```
pi@raspberrypi:~ $ pinout
,--------------------------------.
| oooooooooooooooooooo J8   +======
| 1ooooooooooooooooooo  PoE |   Net
|  Wi                    oo +======
|  Fi  Pi Model 4B  V1.2 oo      |
|        ,----.               +====
| |D|    |SoC |               |USB3
| |S|    |    |               +====
| |I|    `----'                  |
|                   |C|       +====
|                   |S|       |USB2
| pwr   |HD|   |HD| |I||A|    +====
`-| |---|MI|---|MI|----|V|-------'

Revision           : c03112
SoC                : BCM2711
RAM                : 4096Mb
Storage            : MicroSD
USB ports          : 4 (excluding power)
Ethernet ports     : 1
Wi-fi              : True
Bluetooth          : True
Camera ports (CSI) : 1
Display ports (DSI): 1

J8:
   3V3  (1) (2)  5V    
 GPIO2  (3) (4)  5V    
 GPIO3  (5) (6)  GND   
 GPIO4  (7) (8)  GPIO14
   GND  (9) (10) GPIO15
GPIO17 (11) (12) GPIO18
GPIO27 (13) (14) GND   
GPIO22 (15) (16) GPIO23
   3V3 (17) (18) GPIO24
GPIO10 (19) (20) GND   
 GPIO9 (21) (22) GPIO25
GPIO11 (23) (24) GPIO8 
   GND (25) (26) GPIO7 
 GPIO0 (27) (28) GPIO1 
 GPIO5 (29) (30) GND   
 GPIO6 (31) (32) GPIO12
GPIO13 (33) (34) GND   
GPIO19 (35) (36) GPIO16
GPIO26 (37) (38) GPIO20
   GND (39) (40) GPIO21
```


According to your picture, you are using pins 4 (5V), 12 (GPIO18) and 14 (GND).

In the code (best start with [light.desktop](https://github.com/JanLahmann/RasQberry/blob/master/light.desktop) and also look at [rq_LED-test.py](https://github.com/JanLahmann/RasQberry/blob/master/bin/rq_LED-test.py)), we are using LED_PIN=21, i.e GPIO21, which translates to PIN 40 - and is the last one in that row. 

If you use the development branch (and "getgist ... RasQ-init-dev.sh" instead of "get gist ... RasQ-init-dev.sh"), there is an additional demo that can be started with RasQ-LED.desktop on the desktop.

**Comment by hasanakalin** [comment]
Hi Jan. Thanks for your quiclk reply.I tried but I couldn't turn the lights on. I wonder where I could be doing wrong

![IMG_0445](https://user-images.githubusercontent.com/37351958/106647001-6d20be80-659f-11eb-823e-2490b619f509.jpg)
![IMG_0444](https://user-images.githubusercontent.com/37351958/106647012-6f831880-659f-11eb-81aa-b6bbc47b30d8.jpg)
![command](https://user-images.githubusercontent.com/37351958/106647037-79a51700-659f-11eb-8683-996cb5af84c5.JPG)

**Comment by JanLahmann** [comment]
Apologies, my description was incomplete.

It should read:
pin 4 (5V) to IN, (your black cable)
pin 6 to GND. (any other GND would do as well; I just decided to use neighbouring pins 4 and 6)
pin 40 (GPIO21) to VCC, (your white cable)


I think your picture shows VCC connected to pin 12 and GND to pin 40.

**Comment by hasanakalin** [comment]
Hi Jan;

I did as you said although , I still couldn't light on the leds. I really don't know where the problem might be right now

![IMG_0447](https://user-images.githubusercontent.com/37351958/106663565-f1ca0780-65b4-11eb-8226-6bc23006f71d.jpg)
![IMG_0448](https://user-images.githubusercontent.com/37351958/106663574-f42c6180-65b4-11eb-8722-0f232d87fdad.jpg)
![command](https://user-images.githubusercontent.com/37351958/106663598-fc849c80-65b4-11eb-98f6-4a958ea65eef.JPG)

**Comment by JanLahmann** [comment]
Cabling, etc looks good.

You could run the command to start the LEDs directly, without using the raspberry-config menu:
`sudo python3 .local/bin/rq_LED-test.py -c`

And you could try to use other pins for 5V and GND,
and other pins for VCC as listed here: https://github.com/jgarff/rpi_ws281x#gpio-usage

**Comment by hasanakalin** [comment]
Finally let's Work :)) Thank you Jan. You are amazing.For those who have problems like me, I'm writing in detail photos and which pins to attach

IN (BLACK CABLE) = Raspberry PIN (40) GPIO21

VCC(WHITE CABLE) = Raspberry PIN (2) 5V

GND(GRAY CABLE) = Raspberry PIN (6)  GND

command : sudo python3 rq_LED-test.py -c


![IMG_0453](https://user-images.githubusercontent.com/37351958/106751424-33e95c80-663a-11eb-83d6-eda6ea83e7a1.jpg)
![IMG_0454](https://user-images.githubusercontent.com/37351958/106751433-364bb680-663a-11eb-9e51-4634e3bbae9b.jpg)

**Comment by JanLahmann** [comment]
Congratulations!
Apologies, I confused IN and VCC. Your description is correct, of course.
If you like, you could submit a PR for the main README.md and add a short description and a picture for LED cabling and connection.
That would be a big help for the RasQberry project :-)
