### ISSUE TITLE
code conflicting

### ISSUE THREAD

**Issue by hasanakalin** [JanLahmann/RasQberry#39]
hi Jan.I have problem to the rasqberry automatic setup.https://github.com/JanLahmann/RasQberry The hat sense line is not activated when I do the automatic setups on this link. When I install it manually, I add it into the dtoverlay = rpi-sense config.txt file, then it work. I guess it throws a lot of things into the config file in auto setup and doesn't see or open because the files are conflicting
![err (1)](https://user-images.githubusercontent.com/37351958/106584717-9584ca80-6557-11eb-8f70-a78d3d4b14a9.JPG)
[config-new.txt](https://github.com/JanLahmann/RasQberry/files/5910294/config-new.txt)

**Comment by JanLahmann** [comment]
Thank you for the feedback!

It should work when you do the normal setup with raspberry-config:
"Q23 Qiskit 0.23", then "S6 Config & Demos". 

The other config items in the menu should not be run (don't run "S0 Bloch Autostart", "S1 Enable VNC", etc). Not sure if this will create an issue or not.
 
Then you can start the SenseHAT demos with "D2 Raspberry-Tie 5", "D3 Raspberry-Tie 16", or manually with
```
rasqberry

cd ~/qrasp
python main_controller.py 

cd ~/quantum-raspberry-tie
python QuantumRaspberryTie.qiskit.py
```

I think I forgot to document one important step when using a SenseHAT:
Before booting the Raspberry with the fresh SD card, the "#" in following line in /boot/config.txt should be _removed_:
#hdmi_force_hotplug=1

**Comment by hasanakalin** [comment]
thank you so much jan. I fixed this problem. but I think the codes in the repo are expired, I still couldn't run it (edited) 
![ibmm1](https://user-images.githubusercontent.com/37351958/107150820-cb1f1e80-6970-11eb-876c-ace6e51f2225.JPG)
![ibmm](https://user-images.githubusercontent.com/37351958/107150823-cbb7b500-6970-11eb-8358-33ee9e0e752f.JPG)

**Comment by hasanakalin** [comment]
I resolved the problem. Qiskit works with version 0.20, but as I said with the run latest version 0.23, it's give an error. I think the codes need to be updated

**Comment by JanLahmann** [comment]
Oh, yes, that could be.
I haven't tested the SenseHAT demos with Qiskit 0.23, but only with the older versions.
I'll check that. 
Until then, Qiskit 0.20 or 0.19 seems to be needed for the SenseHat based demos (Qrasp, Raspberry-tie).
Thank you for identifying this issue and the workaround!

**Comment by JanLahmann** [comment]
For raspberry-tie, the issue should be solved with the latest updates that repo (https://github.com/KPRoche/quantum-raspberry-tie).
Qrasp also works, if you only use the local simulator, i.e. move the joystick right/left/up/down, but **do not push** the joystick.
In addition, we've fixed our script for storing the IBM Quantum Experience Token, which was broken.
