### ISSUE TITLE
4 inch screen attaached led problem

### ISSUE THREAD

**Issue by hasanakalin** [JanLahmann/RasQberry#43]
I was connected the 4 inch screen to the Raspberry PI, the pins necessary for the LEDs to work are closed. Where do we attach the pins, how do we overcome this problem?
![IMG_0546](https://user-images.githubusercontent.com/37351958/108377171-ce3dc880-7214-11eb-9024-b7f11248e02b.jpg)

**Comment by JanLahmann** [comment]
That depends on the display being used. 
The display listed in the Bill of Material (https://github.com/JanLahmann/RasQberry#bil-of-material) has a 5V and ground pin that can be used to power the LEDs. It is intended for a cooling fan. Either the fan can be left off, or you split the cables to power both the fan and the LEDs.
The pin for the signal (GPIO21 on pin 40) is not covered by the display connector and can be used as without the display.
In case your display does not provide the two pins (5V, -), we'd have to think about a different solution to power the LEDs.

**Comment by hasanakalin** [comment]
hi Jan;

thanks for your quick reply. This is my 800X600 RPI 4 screen

![73386448-5312-4A07-AE0C-4AA5A60F1731](https://user-images.githubusercontent.com/37351958/108408270-e83bd300-7235-11eb-8810-7457ee240c51.jpeg)

**Comment by JanLahmann** [comment]
The display we have listed in the bill-of-material has the two power connectors on the right, which can be used as described above.
<img width="424" alt="image" src="https://user-images.githubusercontent.com/26198628/108412619-49f64000-722a-11eb-9938-db36998c506c.png">

With your display, you could either use a separate 5V power source, or try to use a "GPIO pin doubler" similar to this one https://www.aliexpress.com/i/32601511605.html. However, we have not tried if this works.

**Comment by hasanakalin** [comment]
Thank for your quick reply. I just connected the screen and turned it on. I have hdmi extension DIY cable. but unfortunately the touchscreen doesn't  work because I didn't connect GPIO pins. even if the other suggestion ,There isn't that much space in the back of the box,  RP4 and screen will not fit this box

**Comment by JanLahmann** [comment]
Yes, I think that is correct. The current 3D model only works with the touchscreen that is mentioned in the bill-of-material (https://github.com/JanLahmann/RasQberry#bil-of-material). Other screens might work, but most probably don't fit into the housing. We might consider to provide more flexibility regarding the display types in the future, but that might take some time.
